### ISSUE TITLE
FCNC abbreviates surnames after latest update. 

### ISSUE THREAD

**Issue by kaw-kaw** [WesselKuipers/FCNameColor#34] opened 2023-03-07 21:46 UTC
After the most recent update, FCNameColor seems to abbreviate last names of players in my FC regardless of what my actual setting for "Other PCs" is set to in character config. 

Regardless if I change to Full Name, Surname Abbreviated, Forename Abbreviated or Initials, it will still show Forename + Abbreviated surname. 

If I disable just FCNC, it changes back to whatever my setting is for "Other PCs".

**Comment by wizarduss** [comment] 2023-03-08 08:44
In my case it seems to be the other way around. If it's active Forenames are abbreviated, but surnames stay as is. With the addon deactivated the issue is gone as well.

**Comment by kaw-kaw** [comment] 2023-03-08 08:51
> In my case it seems to be the other way around. If it's active Forenames are abbreviated, but surnames stay as is. With the addon deactivated the issue is gone as well.

It seems to be like this for people that are friendslisted and in my FC, so like this:

FC only: "Firstname S." 
FC + Friend list "F. Surname"

**Comment by WesselKuipers** [comment] 2023-03-08 09:08
Hi, thanks for creating an issue about this!

It turns out that whenever new config options  are added to the game the code for detecting your settings breaks.
Once ClientStructs has been updated things should be like normal again.

**Comment by wizarduss** [comment] 2023-03-08 19:18
is that something that needs to be fixed on dalamud/launcher side?

**Comment by Bechareth** [comment] 2023-03-08 20:35
Also happening for me, First name is the initial, last name is fine. Only in instances, thought I was going insane at first.

**Comment by WesselKuipers** [comment] 2023-03-15 14:22
If you update to the latest testing version (3.0.2.1) it should work again, I'll try and get it released as a regular version tonight, but there have been delays in when plugin updates actually get reviewed and released lately so it might take a little while longer for that to happen.

So in the meantime:
in the `/xlplugins` menu, right click on FCNameColor and click on the option to enable testing versions and it should pop up. If that option is not available, open up the settings (`/xlsettings`) and enable experimental/testing plugin versions, it's somewhere in the last tab of the Dalamud settings.

**Comment by WesselKuipers** [comment] 2023-03-16 14:24
New version should be live now, please let me know if this fixed the issue when you have the time :)

**Closed** 2023-04-30 00:29 UTC
